version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:16
    container_name: identity_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: identity
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Neo4j Service
  neo4j:
    image: neo4j:5
    container_name: profile_neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/neo4j_profile  
      NEO4J_dbms_default__database: neo4jprofile
    ports:
      - "7474:7474"  
      - "7687:7687"  
    volumes:
      - neo4j_data:/data
    networks:
      - neo4j-network

volumes:
  postgres_data:
    driver: local
  neo4j_data:
    driver: local

networks:
  neo4j-network:
    driver: bridge
